<p><a href="<?php echo $this->url(
    array(
        'controller' => 'quickpost',
        'action'     => 'post'
    ),
    'default',
    true) ?>">Post Something</a></p>


    <?php 
	sort($entry);
	foreach ($this->entries as $entry): ?>
   	<hr />
 	<h2><?php echo $this->escape($entry->comment) ?></h2>
    <sup>Posted on: <?php echo $this->escape($entry->created) ?></sup>
	<br /><br />

    <?php endforeach ?>
