<p><a href="<?php echo $this->url(
    array(
        'controller' => 'about',
        'action'     => 'edit'
    ),
    'default',
    true) ?>">Edit</a></p>
    

	<h1><?php 
	sort($entry);
	foreach ($this->entries as $entry): ?>
    <?php echo $this->escape($entry->pagetitle) ?>
    <?php endforeach ?></h1>

	<?php 
	sort($entry);
	foreach ($this->entries as $entry): ?>
    <?php echo $this->escape($entry->content) ?>
    <?php endforeach ?>
<br />

	<sub>Updated on: <?php 
	sort($entry);
	foreach ($this->entries as $entry): ?>
    <?php echo $this->escape($entry->created) ?>
    <?php endforeach ?></sub>


